---
- name: install nginx
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx package is present
    apt:
      name: nginx
      state: present

  - name: Ensure index.html is present
    copy:
      src: index.html
      dest: /var/www/html

  - name: Correct index.html with current date
    lineinfile:
      dest=/var/www/html/index.nginx-debian.html
      regexp="^<h1>"
      insertafter="^<h1>"
      line="<h1><p><script> document.write(new Date().toLocaleDateString());</script></p></h1>"
      state=present

  - name: Ensure ngin service is started
    service:
      name: nginx
      state: started

- name: install db
  hosts: db
  become: yes

  tasks:
  - name: Ensure postgresql is present
    apt:
      name: postgresql
      state: present

  - name: Ensure postgresql service is started
    service:
      name: postgresql
      state: started
